In [50]:
#Modules used 
import pandas as pd 
import numpy as np

In [51]:
df = pd.read_csv("/kaggle/input/linearregression/Data4.csv")
df = df.drop(columns='Sl.')

In [52]:
y = df['y']
y_array = np.array(y)

In [53]:
df = df.drop(columns = 'y')
n = 3

In [54]:
A = np.zeros((n,n))
for i in range(len(df)):
    temp = np.array(df.iloc[i])
    x1 =temp.reshape((n,1))
    x2 =x1.T 
    A += x1@x2
A

array([[3383.5       , 3641.01643904, 3863.4271195 ],
       [3641.01643904, 3929.68278392, 4171.37422047],
       [3863.4271195 , 4171.37422047, 4472.48767615]])

In [55]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[ 0.10108392, -0.09733483,  0.00346332],
       [-0.09733483,  0.11926801, -0.02715837],
       [ 0.00346332, -0.02715837,  0.02256181]])

In [56]:
sigma_yi_xi = np.zeros((n,1))
for i in range(len(df)):
    temp = np.array(df.iloc[i])
    x1 = temp.reshape((n,1))
    x2 = y_array[i].reshape((1,1))
    sigma_yi_xi+=x1@x2
sigma_yi_xi

array([[66074.55450872],
       [71379.27277894],
       [76343.57296322]])

In [57]:
w = A_inverse@sigma_yi_xi
w

array([[-4.21240322],
       [ 8.54119794],
       [12.74220457]])

In [58]:
constant = 1.5  
lst = []
for i in range(len(df)):
    lst.append(w.T @ np.array(df.iloc[i][:]) + constant)
print(lst)

[array([8.7121899]), array([23.82653494]), array([32.13146967]), array([38.35020833]), array([19.48087769]), array([31.58941116]), array([29.7672474]), array([35.00879272]), array([38.94164056]), array([43.12623886]), array([40.63418032]), array([33.61222166]), array([41.19912849]), array([43.20039162]), array([54.55672324]), array([41.9277897]), array([55.97623306]), array([59.53396794]), array([36.2628445]), array([53.33139129]), array([55.88763067]), array([67.53704739]), array([59.61599112]), array([59.05660581]), array([63.88530524]), array([62.73213588]), array([65.29001914]), array([77.3527607]), array([70.08348455]), array([63.35608444]), array([71.82988829]), array([77.61705205]), array([70.75244063]), array([81.70312481]), array([80.42268211]), array([73.49461365]), array([87.37940534]), array([82.92393487]), array([94.790673]), array([86.34188336]), array([98.20330098]), array([83.69917278]), array([75.82522112]), array([80.03505962]), array([107.57544913]), array([109.05288

In [59]:
df['y_hat'] = lst
df['y'] = y_array

In [60]:
def RSS(df):
    return np.sum((df['y']-df['y_hat'])**2)

def TSS(df):
    return np.sum((df['y']-np.mean(df['y_hat']))**2)
def Rsquare(df):
    return 1 - RSS(df) / TSS(df)
print("Rss",RSS(df))
print("TSS",TSS(df))

Rss [4848.83583878]
TSS 218782.86051342316


In [61]:
print(Rsquare(df))

[0.97783722]


In [62]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()

x = df[['x1','x2','x3']]
y = df['y']
lr.fit(x,y)

LinearRegression()

In [63]:
y_hat = lr.predict(x)

In [64]:
r_squared = r2_score(y,y_hat)
r_squared

0.9841749058943147

In [68]:
df =df.drop(columns = 'y_hat')
df

x1         x2         x3           y
0    0.1   0.311089   0.390541   14.705876
1    0.2   0.639066   1.389918   26.585100
2    0.3   0.840228   1.939903   36.791509
3    0.4   1.299710   2.153009   34.090806
4    0.5   0.941784   0.945136   31.118089
..   ...        ...        ...         ...
95   9.6  10.336087   9.979673  183.744594
96   9.7   9.928599  10.721891  175.907274
97   9.8  10.109046  10.163445  183.992845
98   9.9   9.954540  10.562039  173.920425
99  10.0  10.469087  10.727984  179.018755

[100 rows x 4 columns]

In [70]:
y = np.array(df['y'])
df = df.drop(columns='y')

In [76]:
n = 3
def gradient(w):
    res = 0
    sdf = df.sample(frac = 1,axis=1,random_state=42)
    for i in range(len(sdf)):
        r = np.array(sdf.iloc[i][:])
        yhat = r@w
        res +=(y[i]-yhat)*sdf.iloc[i][:]
    return (res*(-2)/len(df)).values.reshape((-1,1))
lr = 0.0001
wi = np.zeros((n,1))
while True:
    wn = wi - lr*gradient(wi)
    up = wi - wn
    down = wn
    if np.linalg.norm(up)/np.linalg.norm(down) <= 1e-4:
        break
    wi = wn 
w = np.array(wi)
print(w)

[[5.53640976]
 [6.02610985]
 [6.5593706 ]]


In [81]:
df

x1         x2         x3   predicted
0    0.1   0.311089   0.390541    9.190003
1    0.2   0.639066   1.389918   18.275355
2    0.3   0.840228   1.939903   23.648770
3    0.4   1.299710   2.153009   28.369148
4    0.5   0.941784   0.945136   18.842995
..   ...        ...        ...         ...
95   9.6  10.336087   9.979673  185.096303
96   9.7   9.928599  10.721891  188.062864
97   9.8  10.109046  10.163445  186.040836
98   9.9   9.954540  10.562039  188.277934
99  10.0  10.469087  10.727984  193.020787

[100 rows x 4 columns]

In [82]:

c = 4.2 
def pred(w):
    lst = []
    for i in range(len(df)):
        res = np.array(df.iloc[i][:])
        res1 = res.reshape((1,-1))
        prediction = w.T @res1.T + c 
        lst.append(prediction.flatten())
    return np.array(lst)

result = pred(w)
print(result)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [80]:
df['predicted'] = result



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [89]:
df['y'] = y
df

x1         x2         x3   predicted           y
0    0.1   0.311089   0.390541    9.190003   14.705876
1    0.2   0.639066   1.389918   18.275355   26.585100
2    0.3   0.840228   1.939903   23.648770   36.791509
3    0.4   1.299710   2.153009   28.369148   34.090806
4    0.5   0.941784   0.945136   18.842995   31.118089
..   ...        ...        ...         ...         ...
95   9.6  10.336087   9.979673  185.096303  183.744594
96   9.7   9.928599  10.721891  188.062864  175.907274
97   9.8  10.109046  10.163445  186.040836  183.992845
98   9.9   9.954540  10.562039  188.277934  173.920425
99  10.0  10.469087  10.727984  193.020787  179.018755

[100 rows x 5 columns]

In [87]:
def r_square(df):
    return 1 - RSS(df)/TSS(df)
def RSS(df):
    return np.sum((df['y'] - df['predicted']) ** 2)
print(RSS(df))
def TSS(df):
    return np.sum((df['y'] - np.mean(df['predicted']))** 2)
print("TSS",TSS(df))
print("Rsquare",r_square(df))

6785.403517357609
TSS 218848.0725028147
Rsquare 0.9689949130474049


In [ ]:
y = np.array(df2['y'])
df = df.drop()