In [ ]:
import numpy as np
import pandas as pd 

In [131]:
df = pd.read_csv("/kaggle/input/linearregression/Data1.csv")
df

x          y
0    0.1   8.298133
1    0.2   4.919282
2    0.3   4.145139
3    0.4   6.850788
4    0.5   6.375323
..   ...        ...
95   9.6  28.420698
96   9.7  27.984652
97   9.8  30.336851
98   9.9  30.376285
99  10.0  27.453770

[100 rows x 2 columns]

In [132]:
y = df['y']
y_array = np.array(y)
df = df.drop(columns='y')

In [133]:
df

x
0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
..   ...
95   9.6
96   9.7
97   9.8
98   9.9
99  10.0

[100 rows x 1 columns]

In [134]:
A = np.zeros((1,1))
for i in range(len(df)):
    temp = np.array(df.iloc[i])
    x1 = temp.reshape((1,1))
    x2 = x1.T
    A+= x1@x2
A

array([[3383.5]])

In [135]:
A_inverse = np.linalg.inv(A)
A_inverse 

array([[0.00029555]])

In [136]:
sigma_yi_xi = np.zeros((1,1))

for i in range(len(df)):
    temp = np.array(df.iloc[i])
    x1 = temp.reshape((1,1))
    x2 = y_array[i].reshape((1,1))
    sigma_yi_xi+= x1*x2
print(sigma_yi_xi)

[[10935.26473252]]


In [137]:
w = A_inverse@sigma_yi_xi
w

array([[3.23193874]])

In [138]:
c = 0.5
lst = []
for i in range(len(df)):
    lst.append(w.T@np.array(df.iloc[i][:] + c))
lst


[array([1.93916325]),
 array([2.26235712]),
 array([2.58555099]),
 array([2.90874487]),
 array([3.23193874]),
 array([3.55513262]),
 array([3.87832649]),
 array([4.20152036]),
 array([4.52471424]),
 array([4.84790811]),
 array([5.17110199]),
 array([5.49429586]),
 array([5.81748974]),
 array([6.14068361]),
 array([6.46387748]),
 array([6.78707136]),
 array([7.11026523]),
 array([7.43345911]),
 array([7.75665298]),
 array([8.07984685]),
 array([8.40304073]),
 array([8.7262346]),
 array([9.04942848]),
 array([9.37262235]),
 array([9.69581623]),
 array([10.0190101]),
 array([10.34220397]),
 array([10.66539785]),
 array([10.98859172]),
 array([11.3117856]),
 array([11.63497947]),
 array([11.95817334]),
 array([12.28136722]),
 array([12.60456109]),
 array([12.92775497]),
 array([13.25094884]),
 array([13.57414272]),
 array([13.89733659]),
 array([14.22053046]),
 array([14.54372434]),
 array([14.86691821]),
 array([15.19011209]),
 array([15.51330596]),
 array([15.83649983]),
 array([16.15969

In [ ]:
df['y_hat'] = lst
df['y'] = y_array

In [ ]:
def R_square(df):
    return 1 - RSS(df)/TSS(df)
def RSS(df):
    return np.sum((df['y']-df['y_hat'])**2)
def TSS(df):
    return np.sum((df['y']-np.mean(df['y_hat']))**2)
print("Rss",RSS(df))
print("TSS",TSS(df))

In [ ]:
R_square(df)

In [ ]:
import matplotlib.pyplot as plt
x_list = [float(i) for i in df['x']]
y_list = [float(i) for i in df['y']]
plt.scatter(x_list, y_list,s=0.4)
plt.plot(x_list, df['y_hat'])
plt.show()

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()

In [ ]:
df
x = df[['x']]
y = df['y']
lr.fit(x,df['y'])

In [ ]:
y_hat = lr.predict(x)
r_square = r2_score(y,y_hat)
print(r_square)

In [ ]:
x_list = [float(i) for i in df['x']]
y_list = [float(i) for i in df['y']]
plt.scatter(x_list, y_list,s=0.3)
plt.plot(x_list, y_hat)
plt.show()

In [ ]:
x = np.array(df['x'])
y = np.array(df['y'])
learning_rate = 0.01


In [ ]:
df = df.drop(columns ='y_hat')
df = df.drop(columns = 'y_hat_g')

In [ ]:
df = df.drop(columns ='y')

In [ ]:
def gradient(w):
    temp = 0
    sdf = df.sample(frac = 1,axis =1 ,random_state=42)
    for i in range(len(sdf)):
        r = np.array(sdf.iloc[i][:])
        yhat = r@w
        temp+= -2*(y[i]-yhat)*sdf.iloc[i][0]/len(sdf)
    return temp

lr = 0.00001
wi = np.zeros((1,1))
while True:
    wn = wi - lr*gradient(wi)
    up = wi - wn
    down = wn
    if np.linalg.norm(up)/np.linalg.norm(down) <= 1e-4:
        break
        
    wi = wn
w = wi
print(w)
    

In [ ]:
c = 4 
def predict(df,w):
    lst = []
    for i in range(len(df)):
        res = np.array(df.iloc[i][:])
        res2 = res.reshape((1,-1))
        prediction = w.T @ res2 + c
        lst.append(prediction.flatten())
    return np.array(lst)
result = predict(df,w)


In [ ]:
df['predicted'] = predict(df,w)
df['y'] = y


In [ ]:
def R_square(df):
    return 1 - RSS(df)/TSS(df)
def RSS(df):
    return np.sum((df['y'] - df['predicted'])**2)
def TSS(df):
    return np.sum((df['y']-np.mean(df['predicted']))**2)

R_square(df)
print("Rss",RSS(df))
print("TSS",TSS(df))

In [ ]:
xlst = [float(i) for i in df['x']]
ylst = [float(i) for i in df['y']]
plt.scatter(xlst,ylst,s=0.5)
plt.plot(xlst,df['predicted'])
plt.show()